version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    commit-message:
      prefix: "deps(github-actions)"
    schedule:
      interval: "daily"
    target-branch: "main"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "analyser"
    commit-message:
      prefix: "deps(python)"
    schedule:
      interval: "monthly"
    target-branch: "main"
    groups:
      python:
        patterns:
          - "*"
