version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    commit-message:
      prefix: "deps(github-actions)"
    schedule:
      interval: "daily"
    target-branch: "main"

  - package-ecosystem: "pip"
    directory: "analyser"
    commit-message:
      prefix: "deps(python)"
    schedule:
      interval: "monthly"
    target-branch: "main"

  - package-ecosystem: "npm"
    directory: "dashboard"
    commit-message:
      prefix: "deps(typescript)"
    schedule:
      interval: "monthly"
    target-branch: "main"
    groups:
      astro:
        patterns:
          - "astro"
          - "@astrojs/*"
