name: "Set Up Python"

runs:
  using: "composite"
  steps:
    - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

    - name: Install Poetry
      shell: bash
      run: |
        pipx install poetry

    - name: Install Python 3.12 with Poetry Cache
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
        cache: "poetry"
        cache-dependency-path: |
          pyproject.toml
          poetry.lock

    - name: Install Poetry Dependencies
      shell: bash
      run: |
        poetry install
