name: "Pull Request Checks"

on:
  pull_request:
    types:
      [
        opened,
        edited,
        unlocked,
        labeled,
        synchronize,
        reopened,
        ready_for_review,
      ]

permissions:
  pull-requests: write

jobs:
  check-pr-title:
    name: Check PR Title
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Title
        uses: deepakputhraya/action-pr-title@v1.0.2
        with:
          allowed_prefixes: "feat:,fix:,bug:,ci:,refactor:,chore(,deps(,chore:,feat!,fix!:,refactor!:" # title should start with the given prefix
  labeller:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v5
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/other-configurations/labeler.yml
          sync-labels: true
