# labels auto assigned to PR, keep in sync with labels.yml
documentation:
  - any:
      - changed-files:
          - any-glob-to-any-file: ["README.md", "docs/**"]
dependencies:
  - any:
      - changed-files:
          - any-glob-to-any-file: ["**/poetry.lock", "**/pyproject.toml"]
      - head-branch: ["^dependabot"]
python:
  - any:
      - changed-files:
          - any-glob-to-any-file: ["*.py", "**/*.py"]
github-pages:
  - any:
      - changed-files:
          - any-glob-to-any-file: ["github-pages/**", "github-pages/**/*"]
just:
  - any:
      - changed-files:
          - any-glob-to-any-file: ["Justfile", "**/*.just"]
github_actions:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              [".github/workflows/*", ".github/workflows/**/*"]
tests:
  - any:
      - changed-files:
          - any-glob-to-any-file: ["**/tests/**"]
