# labels auto assigned to PR, keep in sync with labels.yml
dependencies:
  - any:
      - changed-files:
          - any-glob-to-any-file: ["poetry.lock", "pyproject.toml"]
python:
  - any:
      - changed-files:
          - any-glob-to-any-file: ["*.py"]
github-pages:
  - any:
      - changed-files:
          - any-glob-to-any-file: ["github-pages/**", "github-pages/**/*"]
just:
  - any:
      - changed-files:
          - any-glob-to-any-file: ["Justfile", "*.just"]
automation:
  - any:
      - changed-files:
          - any-glob-to-any-file: [".github/*", ".github/**/*"]
github_actions:
  - any:
      - changed-files:
          - any-glob-to-any-file: [".github/workflows/*", ".github/workflows/**/*"]
