# labels auto assigned to PR, keep in sync with labels.yml
dependencies:
  - pyproject.toml
  - poetry.lock
github-pages:
  - github-pages/**
  - github-pages/**/*
automation:
  - .github/*
  - .github/**/*
